routes/web.php
<?php

Route::get('/teste', function () {
    return view('welcome');
})->middleware('auth'); //tranca rota principal para não passar sem fazer login

Route::group(['prefix'=>'admin', 'namespace'=>'Admin','middleware' => 'auth'], function() {
   Route::get('/', function() { return view('admin.index'); });
   Route::resource('carros', 'CarroController');
   Route::resource('usuario', 'UsuarioController');
   Route::resource('proprietarios', 'ProprietariosController');
   Route::get('carrosgraf','CarroController@graf') -> name('carros.graf');
   Route::any('carrosbuscar','CarroController@buscar') -> name('carros.buscar');
   Route::get('carrosdestaque/{id}','CarroController@destaque') -> name('carros.destaque');
   Route::get('cadcli','ClienteController@form') -> name('cad.cli');
   Route::get('/wsproprietarios/{id?}','ProprietariosController@wsProprietarios');
   Route::get('/wsxmlproprietarios/{id?}','ProprietariosController@wsxmlProprietarios');
   Route::get('/relproprietarios','ProprietariosController@relProprietarios');
});

Route::group(['prefix'=>'site', 'namespace'=>'Site'], function() {
    Route::get('/', function() { return view('site.index'); });
    Route::resource('inicio', 'InicioController');
    Route::resource('principal', 'PrincipalController');
    Route::resource('proposta', 'PropostaController');
    Route::get('propostasgraf','PropostaController@graf') -> name('propostas.graf');
    Route::any('pesquisar','InicioController@pesquisar') -> name('inicio.pesquisar');

});


//Route::get('/admin', function() {
//    return view('admin.index');
//});
Auth::routes(); //após colocar o adminlte no prompt

Route::get('/home', 'HomeController@index')->name('home'); //carrega o index da rota adminlte (tela de login)
//id? quer dizer que ele aceita mesmo se não tiver nada no id
Route::get('/wscarro/{id?}','wsController@wsCarro');

Route::get('/wsxml/{id?}','wsController@wsxml');

Route::get('/listaxml/{preco?}','wsController@listaxml');

Route::get('/rel',function(){
    $pdf = App::make('dompdf.wrapper');
    $pdf->loadHTML('<h1>Test</h1>');
    return $pdf->stream();
});

Route::get('/relcarros','relatController@relcarros');

resources/views/admin/carros_form.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Carros')

@section('content_header')

@if ($acao==1)
<h2>Inclusão de Carros
@else ($acao ==2)
<h2>Alteração de Carros
@endif          

  <a href="{{ route('carros.index') }}" class="btn btn-primary pull-right" role="button">Voltar</a>
</h2>

@endsection

@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if ($acao==1)
<form method="POST" action="{{ route('carros.store') }}"
  enctype="multipart/form-data">
  @else ($acao==2)
  <form method="POST" action="{{route('carros.update', $reg->id)}}"
  enctype="multipart/form-data">
  {!! method_field('put') !!}
  @endif          
  {{ csrf_field() }}

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <label for="modelo">Modelo do Veículo</label>
        <input type="text" id="modelo" name="modelo" required 
               value="{{$reg->modelo or old('modelo')}}"
               class="form-control">
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <label for="marca_id">Marca do Veículo</label>
        <select id="marca_id" name="marca_id" class="form-control">
          @foreach($marcas as $m)
            <option value="{{$m->id}}" 
                    {{ ((isset($reg) and $reg->marca_id == $m->id) or 
                       old('marca_id') == $m->id) ? "selected" : "" }}>
                    {{$m->nome}}</option>
          @endforeach
        </select>  
      </div>
    </div>
  </div>              

  <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label for="cor">Cor</label>
          <input type="text" id="cor" name="cor" required 
                 value="{{$reg->cor or old('cor')}}"
                 class="form-control">
        </div>
      </div>
    
      <div class="col-sm-6">
        <div class="form-group">
            <label for="preco">Preço R$</label>
            <input type="text" id="preco" name="preco" required 
                   value="{{$reg->preco or old('preco')}}"
                   class="form-control">
        </div>
      </div>
  </div>

  <div class="row">
      <div class="col-sm-4">
        <div class="form-group">
          <label for="ano">Ano</label>
          <input type="text" id="ano" name="ano" required 
                 value="{{$reg->ano or old('ano')}}"
                 class="form-control">
        </div>
      </div>

      <div class="col-sm-4">
        <div class="form-group">
          <label for="foto">Foto</label>
          <input type="file" id="foto" name="foto"
                 class="form-control">  
        </div>
      </div>
    
      <div class="col-sm-4">
        <div class="form-group">
            <label for="combustivel">Combustível</label>
            <select id="combustivel" name="combustivel" class="form-control">
                @foreach($comb as $c)
                  <option value="{{$c}}"{{ isset($reg) && $reg->combustivel == $c || old('combustivel') == $c ? "selected":""}}>{{$c}}</option>
                @endforeach
            </select>  
          </div>
      </div>
  </div>

  <input type="submit" value="Enviar" class="btn btn-success">
  <input type="reset" value="Limpar" class="btn btn-warning">
</form>

@endsection

@section('js')
<script src="https://code.jquery.com/jquery-latest.min.js"></script>
<script src="/js/jquery.mask.min.js"></script>
<script>
  $(document).ready(function() {
    $('#preco').mask('#.###.##0,00', {reverse: true});
  });
</script>
@endsection

resources/views/admin/carros_graf.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Carros')

@section('content_header')
    <h1>Gráfico do cadastro de Carros
    <a href="{{ route('carros.index') }}" 
       class="btn btn-primary pull-right" role="button">Listagem</a>
    </h1>
@endsection

@section('content')
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Marcas', 'Número de veículos'],
          //!! faz com que damos um echo para mostrar as linhas desejadas na tela

        @foreach ($dados as $linha)
        
            {!! "['$linha->marca',$linha->num]," !!}

        @endforeach
        ]);

        var options = {
          title: 'Carros por marca',
          pieHole: 0.4,
        };

        var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
        chart.draw(data, options);
      }
    </script>

    <div id="donutchart" style="width: 900px; height: 500px;"></div>


@endsection

resources/views/admin/carros_list.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Carros')

@section('content_header')
    <h1>Cadastro de Carros
    <a href="{{ route('carros.create') }}" 
       class="btn btn-primary pull-right" role="button">Novo</a>
    </h1>
@endsection

@section('content')

@if (session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>  
@endif

<table class="table table-striped">
  <tr>
    <th> Modelo </th>
    <th> Marca </th>
    <th> Cor </th>
    <th> Ano </th>
    <th> Preço R$ </th>
    <th> Combustível </th>
    <th> Data Cad. </th>
    <th> * </th>
    <th> Foto </th>
    <th> Ações </th>
  </tr>  
@forelse($carros as $c)
  <tr>
    <td> {{$c->modelo}} </td>
    <td> {{$c->marca->nome}} </td>
    <td> {{$c->cor}} </td>
    <td> {{$c->ano}} </td>
    <td> {{number_format($c->preco, 2, ',', '.')}} </td>
    <td> {{$c->combustivel}} </td>
    <td> {{date_format($c->created_at, 'd/m/Y')}} </td>
    <td> {{$c->destaque}} </td>
    <td> @if(Storage::exists($c->foto))
          <img src="{{url('storage/'.$c->foto)}}"
          style="width: 80px; height: 50px"
          alt="Foto de Carro">
        @else
        <img src="{{url('storage/fotos/semfoto.jpeg')}}"
          style="width: 80px; height: 50px"
          alt="Sem Foto">
        @endif
   </td>
    <td> 
        <a href="{{route('carros.edit', $c->id)}}" 
            class="btn btn-warning btn-sm" title="Alterar"
            role="button"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
        <form style="display: inline-block"
              method="post"
              action="{{route('carros.destroy', $c->id)}}"
              onsubmit="return confirm('Confirma Exclusão?')">
               {{method_field('delete')}}
               {{csrf_field()}}
              <button type="submit" title="Excluir"
                      class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
        </form>&nbsp;&nbsp;  
        <a href="{{route('carros.destaque', $c->id)}}" 
            class="btn btn-success btn-sm" title="Destacar"
            role="button">
            @if($c ->destaque == "*" )
              <i class="fa fa-star"></i></a>
            @else
              <i class="far fa-star"></i></a>
            @endif
    </td>
  </tr>
  @if ($loop->last)
    <tr>
      <td colspan=8> Soma dos preços dos veículos cadastrados R$: 
        {{number_format($soma, 2, ',', '.')}} </td>
    </tr>  
    <tr>
      <td colspan=8> Preço Médio dos veículos cadastrados R$: 
        {{number_format($c->avg('preco'), 2, ',', '.')}} </td>
    </tr>  
  @endif

@empty
  <tr><td colspan=8> Não há carros cadastrados ou filtro da pesquisa não 
                     encontrou registros </td></tr>
@endforelse
</table>

{{ $carros->links() }}

@endsection

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection

resources/views/admin/clientes_form.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Clientes')

@section('content_header')

@if ($acao==1)
<h2>Inclusão de Clientes
@else ($acao ==2)
<h2>Alteração de Clientes
@endif          

  <a href="{{ route('carros.index') }}" class="btn btn-primary pull-right" role="button">Voltar</a>
</h2>

@endsection

@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if ($acao==1)
<form method="POST" action="{{ route('carros.store') }}"
  enctype="multipart/form-data">
  @else ($acao==2)
  <form method="POST" action="{{route('carros.update', $reg->id)}}"
  enctype="multipart/form-data">
  {!! method_field('put') !!}
  @endif          
  {{ csrf_field() }}

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <label for="nome">Nome do cliente</label>
        <input type="text" id="nome" name="nome" required class="form-control">
      </div>
    </div>

    <div class="col-sm-6">
      <div class="form-group">
        <label for="email">E-mail</label>
        <input id="email" name="email" required class="form-control"> 
      </div>
    </div>
  </div>              

  <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label for="cep">Cep</label>
          <input type="text" id="cep" name="cep" required class="form-control">
        </div>
      </div>
    
      <div class="col-sm-6">
        <div class="form-group">
            <label for="endereco">Endereço</label>
            <input type="text" id="endereco" name="endereco" required class="form-control">
        </div>
      </div>
  </div>

  <div class="row">
      <div class="col-sm-5">
        <div class="form-group">
          <label for="bairro">Bairro</label>
          <input type="text" id="bairro" name="bairro" required class="form-control" readonly>
        </div>
      </div>

      <div class="col-sm-5">
        <div class="form-group">
          <label for="cidade">Cidade</label>
          <input type="text" id="cidade" name="cidade" required class="form-control" readonly>  
        </div>
      </div>
    
      <div class="col-sm-2">
        <div class="form-group">
            <label for="estado">Estado</label>
            <input type:"text" id="estado" name="estado" required class="form-control" readonly> 
          </div>
      </div>
  </div>

  <input type="submit" value="Enviar" class="btn btn-success">
  <input type="reset" value="Limpar" class="btn btn-warning">
</form>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.js"></script>
        <script>
                $('#cep').mask('00.000-000', {reverse: true});
        </script>

@endsection

@section('js')
<script src="/js/buscacep.js"></script>
@endsection

resources/views/admin/index.blade.php
@extends('adminlte::page')

@section('title', 'Principal')

@section('content_header')
    <h1>Dashboard</h1>
@stop

@section('content')
    <p>Welcome to this beautiful admin panel.</p>
@stop

resources/views/admin/proposta_graf.blade.php
@extends('adminlte::page')

@section('title', 'Gráfico de propostas')

@section('content_header')
    <h1>Gráfico de propostas mensais
    <a href="{{ route('proposta.index') }}" 
       class="btn btn-primary pull-right" role="button">Listagem</a>
    </h1>
@endsection

@section('content')
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Propostas', 'Nº Propostas'],
          //!! faz com que damos um echo para mostrar as linhas desejadas na tela

        @foreach ($dados as $linha)
        
            {!! "['$linha->mes',$linha->num]," !!}

        @endforeach
        ]);

        var options = {
          title: 'Nº de Propostas por Mês',
          pieHole: 0.4,
        };

        var chart = new google.visualization.PieChart(document.getElementById('donutchart'));
        chart.draw(data, options);
      }
    </script>

    <div id="donutchart" style="width: 900px; height: 500px;"></div>


@endsection

resources/views/admin/proprietarios_form.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Proprietarios')

@section('content_header')

@if ($acao==1)
<h2>Inclusão de Proprietários
@else ($acao ==2)
<h2>Alteração de Proprietários
@endif          

  <a href="{{ route('proprietarios.index') }}" class="btn btn-primary pull-right" role="button">Voltar</a>
</h2>

@endsection

@section('content')

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if ($acao==1)
<form method="POST" action="{{ route('proprietarios.store') }}"
  enctype="multipart/form-data">
  @else ($acao==2)
  <form method="POST" action="{{route('proprietarios.update', $reg->id)}}"
  enctype="multipart/form-data">
  {!! method_field('put') !!}
  @endif          
  {{ csrf_field() }}

    <div class="row">
        <div class="col-sm-6">
            <div class="form-group">
            <label for="nome">Nome do Proprietário</label>
            <input type="text" id="nome" name="nome" required 
               value="{{$reg->nome or old('nome')}}"
               class="form-control">
            </div>
        </div>             

      <div class="col-sm-6">
        <div class="form-group">
          <label for="email">E-mail</label>
          <input type="email" id="email" name="email" required 
                 value="{{$reg->email or old('email')}}"
                 class="form-control">
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
            <label for="telefone">Telefone</label>
            <input type="text" id="telefone" name="telefone" required 
                   value="{{$reg->telefone or old('telefone')}}"
                   class="form-control">
        </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label for="cidade">Cidade</label>
          <input type="text" id="cidade" name="cidade" required 
                 value="{{$reg->cidade or old('cidade')}}"
                 class="form-control">
        </div>
      </div>
    </div>

  <input type="submit" value="Enviar" class="btn btn-success">
  <input type="reset" value="Limpar" class="btn btn-warning">
</form>

@endsection

@section('js')
<script src="https://code.jquery.com/jquery-latest.min.js"></script>
<script src="/js/jquery.mask.min.js"></script>
<script>
  $(document).ready(function() {
    $('#telefone').mask('(00) 0 0000-0000');
  });
</script>
@endsection

resources/views/admin/proprietarios_lista.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Proprietarios')

@section('content_header')
    <h1>Cadastro de Proprietários
    <a href="{{ route('proprietarios.create') }}" 
       class="btn btn-primary pull-right" role="button">Novo</a>
    </h1>
@endsection

@section('content')

@if (session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>  
@endif

<table class="table table-striped">
  <tr>
    <th> Nome </th>
    <th> E-mail </th>
    <th> Telefone </th>
    <th> Cidade </th>
    <th> Ações </th>
  </tr>  
@forelse($proprietarios as $p)
  <tr>
    <td> {{$p->nome}} </td>
    <td> {{$p->email}} </td>
    <td> {{$p->telefone}} </td>
    <td> {{$p->cidade}} </td>
    <td> 
        <a href="{{route('proprietarios.edit', $p->id)}}" 
            class="btn btn-warning btn-sm" title="Alterar"
            role="button"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
        <form style="display: inline-block"
              method="post"
              action="{{route('proprietarios.destroy', $p->id)}}"
              onsubmit="return confirm('Confirma Exclusão?')">
               {{method_field('delete')}}
               {{csrf_field()}}
              <button type="submit" title="Excluir"
                      class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
        </form>&nbsp;&nbsp;
    </td>
  </tr>
@empty
  <tr><td colspan=8> Não há proprietários cadastrados. </td></tr>
@endforelse
</table>

@endsection

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection

resources/views/admin/relatorio_proprietarios.blade.php
<h1>Revenda Herbie</h1>
<h2>Relatório de Proprietários Cadastrados</h2>

<table border=1>
    <tr><td>Nome</td>
    <td>E-mail</td>
    <td>Telefone</td>
    <td>Cidade</td>
    </tr>

    @foreach($proprietarios as $p)
        <tr><td>{{$p->nome}}</td>
        <td>{{$p->email}}</td>
        <td>{{$p->telefone}}</td>
        <td>{{$p->cidade}}</td>
        </tr>
    @endforeach
</table>

resources/views/admin/relcarros.blade.php
<h1>Revenda Herbie</h1>
<h2>Relatório de Veículos Cadastrados</h2>

<table border=1>
    <tr><td>Modelo</td>
    <td>Ano</td>
    <td>Preço R$:</td>
    </tr>

    @foreach($carros as $c)
        <tr><td>{{$c->modelo}}</td>
        <td>{{$c->ano}}</td>
        <td>{{number_format($c->preco, 2, ',', '.')}}</td>
        </tr>
    @endforeach
</table>

resources/views/admin/usuario_list.blade.php
@extends('adminlte::page')

@section('title', 'Cadastro de Carros')

@section('content_header')
    <h1>Cadastro de Carros
    <a href="{{ route('usuario.create') }}" 
       class="btn btn-primary pull-right" role="button">Novo</a>
    </h1>
@endsection

@section('content')

@if (session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>  
@endif

<table class="table table-striped">
  <tr>
    <th> Id </th>
    <th> Nome </th>
    <th> E-mail </th>
    <th> Data de criação </th>
    <th> Ações </th>
  </tr>  
@forelse($usuario as $c)
  <tr>
    <td> {{$c->id}} </td>
    <td> {{$c->name}} </td>
    <td> {{$c->email}} </td>
    <td> {{$c->creatd_at}} </td>
    <td> 
        <a href="{{route('usuario.edit', $c->id)}}" 
            class="btn btn-warning btn-sm" title="Alterar"
            role="button"><i class="fa fa-edit"></i></a> &nbsp;&nbsp;
        <form style="display: inline-block"
              method="post"
              action="{{route('usuario.destroy', $c->id)}}"
              onsubmit="return confirm('Confirma Exclusão?')">
               {{method_field('delete')}}
               {{csrf_field()}}
              <button type="submit" title="Excluir"
                      class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
        </form>  
    </td>
  </tr>
@empty
  <tr><td colspan=8> Não há usuario cadastrados ou filtro da pesquisa não 
                     encontrou registros </td></tr>
@endforelse
</table>



@endsection

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection