routes/web.php
<?php

Route::get('/teste', function () {
    return view('welcome');
})->middleware('auth'); //tranca rota principal para não passar sem fazer login

Route::group(['prefix'=>'admin', 'namespace'=>'Admin','middleware' => 'auth'], function() {
   Route::get('/', function() { return view('admin.index'); });
   Route::resource('carros', 'CarroController');
   Route::resource('usuario', 'UsuarioController');
   Route::resource('proprietarios', 'ProprietariosController');
   Route::get('carrosgraf','CarroController@graf') -> name('carros.graf');
   Route::any('carrosbuscar','CarroController@buscar') -> name('carros.buscar');
   Route::get('carrosdestaque/{id}','CarroController@destaque') -> name('carros.destaque');
   Route::get('cadcli','ClienteController@form') -> name('cad.cli');
   Route::get('/wsproprietarios/{id?}','ProprietariosController@wsProprietarios');
   Route::get('/wsxmlproprietarios/{id?}','ProprietariosController@wsxmlProprietarios');
   Route::get('/relproprietarios','ProprietariosController@relProprietarios');
});

Route::group(['prefix'=>'site', 'namespace'=>'Site'], function() {
    Route::get('/', function() { return view('site.index'); });
    Route::resource('inicio', 'InicioController');
    Route::resource('principal', 'PrincipalController');
    Route::resource('proposta', 'PropostaController');
    Route::get('propostasgraf','PropostaController@graf') -> name('propostas.graf');
    Route::any('pesquisar','InicioController@pesquisar') -> name('inicio.pesquisar');

});


//Route::get('/admin', function() {
//    return view('admin.index');
//});
Auth::routes(); //após colocar o adminlte no prompt

Route::get('/home', 'HomeController@index')->name('home'); //carrega o index da rota adminlte (tela de login)
//id? quer dizer que ele aceita mesmo se não tiver nada no id
Route::get('/wscarro/{id?}','wsController@wsCarro');

Route::get('/wsxml/{id?}','wsController@wsxml');

Route::get('/listaxml/{preco?}','wsController@listaxml');

Route::get('/rel',function(){
    $pdf = App::make('dompdf.wrapper');
    $pdf->loadHTML('<h1>Test</h1>');
    return $pdf->stream();
});

Route::get('/relcarros','relatController@relcarros');

app/Http/Controllers/Site/InicioController.php
<?php

namespace App\Http\Controllers\Site;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use App\Carro;
use App\Marca;

class InicioController extends Controller
{
    public function index(){
            
            $dados = DB::select("SELECT * FROM carros WHERE destaque = '*'");
            return view('site.inicio_lista',['carros' => $dados]);

    }
    public function show($id) {

   }

   public function create() {
       
       
   }

   public function store(Request $request) {
       

   }

   public function edit($id) {
   

    }

   public function update(Request $request, $id) {
       
   }

   public function destroy($id){
   
   }

   public function pesquisar(request $request){
        $modelo = $request->modelo;
        $filtro = array();
        if(!empty($modelo)){
                array_push($filtro, array('modelo','like','%'.$modelo.'%'));
        }

        $carros = Carro::where($filtro)->orderBy('modelo')->paginate(5);
        return view('site.carros_pesquisa',compact('carros'));

       //$texto = Input::any('texto');
        //$sql="select * from carros where modelo like %".$texto."%";
        //$pesquisa = Produtos::where('modelo', 'like', '%'.$texto.'%');

        //$dados = DB::select($sql);

        //return view('inicio.pesquisar', ['dados'=>$dados]);
        //$user = DB::table('carros')->where('modelo', 'sandero')->first();
        
        //echo "haha";
        }
}

app/Http/Controllers/Site/PrincipalController.php
<?php

namespace App\Http\Controllers\Site;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use App\Carro;
use App\Marca;

class PrincipalController extends Controller
{
    public function index(){

        $dados = Carro::all();
        return view('site.principal_lista', ['carros' => $dados]);
            

    }
    public function show($id) {

   }

   public function create() {
       
       
   }

   public function store(Request $request) {
       

   }

   public function edit($id) {
   

    }

   public function update(Request $request, $id) {
       
   }

   public function destroy($id){
   
   }
}

app/Http/Controllers/Site/PropostaController.php
<?php

namespace App\Http\Controllers\Site;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;
use App\Carro;
use App\Marca;
use App\Proposta;

class PropostaController extends Controller
{
    public function index(){

        $dados = Proposta::all();
        return view('site.proposta_list', ['propostas' => $dados]);

    }
    public function show($id) {
        $reg = Carro::find($id);
        return view('site.proposta_form', ['reg' => $reg]);

   }

   public function create() {
       
       
   }

   public function store(Request $request) {

    $this->validate($request, [
        'nome' => 'required|min:2|max:200',
        'email' => 'required',
        'telefone' => 'min:9|max:40'
    ]);
    $request['proposta'] = str_replace(',','.',str_replace('.','',$request['proposta']));

    //$request['data']=date_format('y-m-d',$request['data']);
    //$request['data'] = date_format("y-m-d",$request['data']);
    //$request['data'] = str_replace('/',str_replace('-',$request['data']));
        
    Proposta::create($request->all());

    return redirect()->route('principal.index')
        ->with('status','Proposta inserida com sucesso!');
       

   }

   public function edit($id) {
   

    }

   public function update(Request $request, $id) {
       
   }

   public function destroy($id){

    $prop = Proposta::find($id);

        if ($prop->delete()) {

            return redirect()->route('proposta.index')
                        ->with('status', 'Proposta de id '.$prop->id.' do cliente '.$prop->nome.' excluída!');
        }
    }
    
    public function graf(){

        $sql = "select concat(year(data), '-', month(data)) as mes,  
        count(*) as num 
        from propostas 
        group by concat(year(data), '-', month(data))";

                $dados = DB::select($sql);

        return view('admin.proposta_graf', ['dados' => $dados]);
    }
}

resources/views/site/carros_pesquisa.blade.php
@extends('site.modelo')

@section('conteudo')
<br>
<div class="container">
<div class="row">
@forelse($carros as $c)
        <div class="col col-sm-4">
            <div class="card border-primary bg-light">
                <div class="card-header text-center" style="font-weight: bold;">{{ $c->modelo }}</div>
                    <div class="card-body">
                        @if(Storage::exists($c->foto))
                            <img src="{{url('storage/'.$c->foto)}}"
                            style="width: 100%; height: 150px;" 
                            alt="Foto de Carro"/>
                        @else
                            <img src="{{url('storage/fotos/sem_foto.png')}}"
                            style="width: 100%; height: 150px;" 
                            alt="Foto de Carro"/>
                        @endif
                        <hr>
                        <p class="text-center">Valor R$: {{number_format($c->preco, 2, ',', '.')}} </p>
                        <a href="{{ route('proposta.index') }}/{{ $c->id }}" class="btn btn-block btn-outline-dark" role="button">Proposta</a>
                    </div>
                </div>
                <br>
        </div>

@empty
        <h4>Não existe(m) carro(s) cadastrados com este nome !</h4>

@endforelse
</div>
</div>
@endsection

resources/views/site/inicio_lista.blade.php
@extends('site.modelo')

@section('conteudo')
<br>
<div class="container">
<div class="row">
@forelse($carros as $c)
        <div class="col col-sm-4">
            <div class="card border-primary bg-light">
                <div class="card-header text-center" style="font-weight: bold;">{{ $c->modelo }}</div>
                    <div class="card-body">
                        @if(Storage::exists($c->foto))
                            <img src="{{url('storage/'.$c->foto)}}"
                            style="width: 100%; height: 150px;" 
                            alt="Foto de Carro"/>
                        @else
                            <img src="{{url('storage/fotos/sem_foto.png')}}"
                            style="width: 100%; height: 150px;" 
                            alt="Foto de Carro"/>
                        @endif
                        <hr>
                        <p class="text-center">Valor R$: {{number_format($c->preco, 2, ',', '.')}} </p>
                        <a href="{{ route('proposta.index') }}/{{ $c->id }}" class="btn btn-block btn-outline-dark" role="button">Proposta</a>
                    </div>
                </div>
                <br>
        </div>

@empty
        <h4>Não existe(m) carro(s) em destaque no momento !</h4>

@endforelse
</div>
</div>
@endsection

resources/views/site/modelo.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>Revenda Herbie</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
</head>
<body>



<nav class="navbar navbar-expand-sm bg-primary navbar-dark">
  <ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link" href="{{ route('inicio.index') }}">Início</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ route('principal.index') }}">Carros</a>
    </li>
  
    <form class="form-inline" role="search" action="{{ route('inicio.pesquisar') }}" method="post" style="margin-left: 200%;">
    {!! csrf_field() !!}
      <input class="form-control mr-sm-2" type="text" name="modelo" id="modelo" placeholder="Buscar carros">
    </form>

  </ul>
</nav>

@yield('conteudo')
</body>
</html>

resources/views/site/principal_lista.blade.php
@extends('site.modelo')

@section('conteudo')

@if (session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>  
@endif

<br>
<div class="container">
<div class="row">
@forelse($carros as $c)
        <div class="col col-sm-4">
            <div class="card border-primary bg-light">
                <div class="card-header text-center" style="font-weight: bold;">{{ $c->modelo }}</div>
                    <div class="card-body">
                        @if(Storage::exists($c->foto))
                            <img src="{{url('storage/'.$c->foto)}}"
                            style="width: 100%; height: 150px;" 
                            alt="Foto de Carro"/>
                        @else
                            <img src="{{url('storage/fotos/sem_foto.png')}}"
                            style="width: 100%; height: 150px;" 
                            alt="Foto de Carro"/>
                        @endif
                        <hr>
                        <p class="text-center">Valor R$: {{number_format($c->preco, 2, ',', '.')}} </p>
                        <a href="{{ route('proposta.index') }}/{{ $c->id }}" class="btn btn-block btn-outline-dark" role="button">Proposta</a>
                    </div>
                </div>
                <br>
        </div>

@empty
        <h4>Não Existe carros sendo Exibidos</h4>

@endforelse
</div>
</div>
@endsection

resources/views/site/proposta_form.blade.php
@extends('site.modelo')

@section('conteudo')


    <div class="container">
        <h2>Envie sua proposta</h2>
  

        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <form method="post" class="form-group" action="{{route('proposta.store')}}">
                    {{ csrf_field() }}

                    <label for="nome" class="mr-sm-2">Nome: </label>
                    <input type="text" id="nome" name="nome" class="form-control" required>

                    <label for="email" class="mr-sm-2">E-mail: </label>
                    <input type="email" id="email" name="email" class="form-control" required>

                    <label for="telefone" class="mr-sm-2">Fone: </label>
                    <input type="text" id="telefone" name="telefone" class="form-control" required>

                    <label for="data" class="mr-sm-2">Data : </label>
                    <input type="date" id="data" name="data" class="form-control" required>

                    <label for="proposta" class="mr-sm-2">Valor da proposta: </label>
                    <input type="text" id="proposta" name="proposta" class="form-control" required>

                    <br>
                    <input type="hidden" name="veiculo_id" value="{{$reg->id}}">
                    <button type="submit" class="btn btn-success">Enviar</button>
                    <input type="reset" value="Limpar" class="btn btn-warning">
                    </form>
                </div>

                <div class="col-sm-4">
                @if(Storage::exists($reg->foto))
                    <img src="{{url('storage/'.$reg->foto)}}"
                        style="width: 100%; height: 150px;" 
                        alt="Foto de Carro"/>
                @else
                    <img src="{{url('storage/fotos/sem_foto.png')}}"
                        style="width: 100%; height: 150px;" 
                        alt="Foto de Carro"/>
                @endif
                <ul class="none">
                    <li><b><i class="fas fa-car"></i></b> {{$reg->modelo}}</li>
                    <li><b> <i class="far fa-calendar-alt"></i></b> {{$reg->ano}}</li>
                    <li><b><i class="fas fa-ticket-alt"></i></b> {{$reg->marca->nome}}</li>
                    <li><b><i class="fas fa-gas-pump"></i></b> {{$reg->combustivel}}</li>
                    <li><h2><i class="fas fa-dollar-sign"></i>{{ number_format($reg->preco, '2', ',', '.')}}</h2></li>
                </ul>
            </div>
        </div>
    </div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.js"></script>
        <script>
            $(document).ready(function () {
                $('#proposta').mask('0.000.000,00', {reverse: true});
                $('#telefone').mask('(00) 0 0000-0000');
                            });
        </script>
@endsection

resources/views/site/proposta_list.blade.php
@extends('adminlte::page')

@section('title', 'Lista de propostas')

@section('content')

@if (session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>  
@endif

<table class="table table-striped">
  <tr>
    <th> Nome </th>
    <th> E-mail </th>
    <th> Telefone </th>
    <th> Proposta </th>
    <th> Data </th>
    <th> ID do Veículo </th>
    <th> Ações </th>
  </tr>  
@forelse($propostas as $c)
  <tr>
    <td> {{$c->nome}} </td>
    <td> {{$c->email}} </td>
    <td> {{$c->telefone}} </td>
    <td> {{$c->proposta}} </td>
    <td> {{$c->data}} </td>
    <td> {{$c->veiculo_id}} </td>
   </td>
    <td> 
        <form style="display: inline-block"
              method="post"
              action="{{route('proposta.destroy', $c->id)}}"
              onsubmit="return confirm('Confirma Exclusão?')">
               {{method_field('delete')}}
               {{csrf_field()}}
              <button type="submit" title="Excluir"
                      class="btn btn-danger btn-sm"><i class="far fa-trash-alt"></i></button>
        </form>&nbsp;&nbsp;
    </td>
  </tr>

@empty
  <tr><td colspan=8> Não há propostas cadastradas ou filtro da pesquisa não 
                     encontrou registros </td></tr>
@endforelse
</table>

@endsection

@section('js')
  <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>
@endsection